In [2]:
import numpy as np
from numpy import random

### What is a Random Number?
Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

In [16]:
x = random.randint(100)
print(x)

38


In [14]:
x = random.randint(1, 100) if random.randint(1, 100) % 2 == 0 else 1
print(x)

1


In [30]:
x = random.randint(range(1,100))

by_two= [] 
by_two.append( x % 2 == 0)
by_thre = []
by_thre.append(x % 3 == 0) 
print(x)
print(by_two)
print(by_thre)

[ 0  0  0  0  2  4  0  1  1  8  1 11  5  6  9  9  6 12  2 17 13  0 19 20
  1 15 21  2 17 28 12 11  1 29 15  7 34  3 19 37 14 28 23  9 27 44 12  1
 48 46 29  2 39 36 48  7 27 24 27 59 31 39 22 61 27 31  1 21 66 63 49  1
 63 53  0  7 63 44 53 47 28 79 24 78 31 54 28  9 67 87  4 81 10 56 30  4
  0  0 14]
[array([ True,  True,  True,  True,  True,  True,  True, False, False,
        True, False, False, False,  True, False, False,  True,  True,
        True, False, False,  True, False,  True, False, False, False,
        True, False,  True,  True, False, False, False, False, False,
        True, False, False, False,  True,  True, False, False, False,
        True,  True, False,  True,  True, False,  True, False,  True,
        True, False, False,  True, False, False, False, False,  True,
       False, False, False, False, False,  True, False, False, False,
       False, False,  True, False, False,  True, False, False,  True,
       False,  True,  True, False,  True,  True, False, False, Fal

In [36]:
x = random.randint(range(1, 100))


by_two= (x % 2 == 0)
by_thre = (x % 3 == 0)
print( by_two == True )

[ True False False  True  True  True False  True  True  True  True  True
 False  True  True  True False False  True  True False  True  True  True
  True False False  True False  True  True  True  True False  True False
 False  True  True  True  True False False  True False  True  True False
  True  True  True  True  True False  True  True False  True False  True
  True  True False False  True  True  True False False  True  True False
  True False False False False  True False False False False  True  True
  True  True  True False False  True False  True False  True  True False
 False False False]


In [40]:
x = random.rand() # generate random no between 0 and 1
print(x)

0.16762301244615718


### Generate Random Array

In [43]:
x = random.randint(100, size=(5))
print(x)

[18 42 43 80 73]


In [46]:
x = random.randint(100, size=(5,3))
print(x)

[[ 4 56 60]
 [67 61 59]
 [ 8  1 75]
 [32 44 17]
 [30 58 38]]


In [49]:
x = random.rand(5)
print(x)

[0.89356948 0.71215406 0.90909295 0.73646389 0.93972669]


In [52]:
x = random.rand(5,3)
print(x)

[[0.45083266 0.54683571 0.87848223]
 [0.79840767 0.16111319 0.13936553]
 [0.21679216 0.50728636 0.5446674 ]
 [0.53319949 0.6210119  0.6541778 ]
 [0.87606437 0.971253   0.70113966]]


In [55]:
x = random.choice([1,23,3,4])
print(x)

1


In [58]:
x = random.choice([1,3,4,4], size=(3,5))
print(x)

[[4 3 3 1 4]
 [4 3 4 1 3]
 [3 3 4 1 3]]
