In [2]:
import numpy as np

In [3]:
arr = [1,3,4,5,6,7,8,9]
arr = np.array(arr)
print(arr)
print(type(arr))

[1 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [4]:
arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
arr = np.array(["hello","world"])
print(arr)
print(type(arr))

['hello' 'world']
<class 'numpy.ndarray'>


In [6]:
arr = np.array(1)
print(arr)
print(type(arr))

1
<class 'numpy.ndarray'>


In [7]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
arr = np.array([[1,3,4,5,6],[7,8,9,10,11]])
print(arr)
print(type(arr))
print(arr.shape)

[[ 1  3  4  5  6]
 [ 7  8  9 10 11]]
<class 'numpy.ndarray'>
(2, 5)


In [9]:
arr = np.array([[[1,2,3,4],[5,6,7,8]]])
print(arr)
print(type(arr))
print(arr.shape)

[[[1 2 3 4]
  [5 6 7 8]]]
<class 'numpy.ndarray'>
(1, 2, 4)


In [10]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [11]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [12]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [13]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [14]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [15]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('2nd element on 1st row: ', arr[0, 1])
print(arr[0][1])

2nd element on 1st row:  2
2


In [16]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('5th element on 2nd row: ', arr[1, 4])
print(arr[1][4])

5th element on 2nd row:  10
10


In [17]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
print(arr[0][1][2])

6
6


In [18]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('Last element from 2nd dim: ', arr[1, -1])
print(arr[1][-1])

Last element from 2nd dim:  10
10


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[0:len(arr)]
arr[1:5]


array([2, 3, 4, 5])

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [25]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:4])
print(arr[0][1:4])

[2 3 4]
[2 3 4]


In [26]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [27]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [28]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [29]:
arr = np.array([1, 2, 3, 4],dtype='S')

print(arr.dtype)

|S1


In [30]:

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [31]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [32]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [33]:
arr = np.array([1, 2, 3, 4, 5])
arr1 = [ arr.copy() * 3 for arr in arr if arr % 2 == 0]
print(arr)
print(arr1)

[1 2 3 4 5]
[6, 12]


In [34]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

print(x.base)
print(arr.base)

[42  2  3  4  5]
[42  2  3  4  5]
[42  2  3  4  5]
None


In [35]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [36]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr = print(arr.reshape(2, 4).base)
print(arr)

[1 2 3 4 5 6 7 8]
None


In [39]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [41]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(f"with Respect to {x} : {y}".format(x,y))

with Respect to [1 2 3] : 1
with Respect to [1 2 3] : 2
with Respect to [1 2 3] : 3
with Respect to [4 5 6] : 4
with Respect to [4 5 6] : 5
with Respect to [4 5 6] : 6


In [43]:
arr = np.array([
    [
    [1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]
    ]
])

for x in arr:
  for y in arr:
    for z in arr:
        print(z)
        print(f"with Respect to {x} : {y} : {z}".format(x,y,z))

[[1 2 3]
 [4 5 6]]
with Respect to [[1 2 3]
 [4 5 6]] : [[1 2 3]
 [4 5 6]] : [[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
with Respect to [[1 2 3]
 [4 5 6]] : [[1 2 3]
 [4 5 6]] : [[ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
with Respect to [[1 2 3]
 [4 5 6]] : [[ 7  8  9]
 [10 11 12]] : [[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
with Respect to [[1 2 3]
 [4 5 6]] : [[ 7  8  9]
 [10 11 12]] : [[ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
with Respect to [[ 7  8  9]
 [10 11 12]] : [[1 2 3]
 [4 5 6]] : [[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
with Respect to [[ 7  8  9]
 [10 11 12]] : [[1 2 3]
 [4 5 6]] : [[ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
with Respect to [[ 7  8  9]
 [10 11 12]] : [[ 7  8  9]
 [10 11 12]] : [[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
with Respect to [[ 7  8  9]
 [10 11 12]] : [[ 7  8  9]
 [10 11 12]] : [[ 7  8  9]
 [10 11 12]]


In [44]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [45]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [46]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [47]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [48]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [49]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [50]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [51]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [52]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [53]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [54]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [55]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [56]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [57]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [59]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [60]:

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [61]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [62]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [63]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [64]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [65]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [66]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [67]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [68]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [69]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [70]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [72]:
print(np)

<module 'numpy' from 'c:\\Users\\abdul\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
