### Random Permutations of Elements
- A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.
- The NumPy Random module provides two methods for this: shuffle() and permutation().

In [1]:
import numpy as np 
from numpy import random

In [12]:
x = np.array([1,2,3,4])
print(x)
# The shuffle() method makes changes to the original array.
random.shuffle(x)
print(x)

[1 2 3 4]
[1 2 4 3]


In [24]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x)

# The permutation() method returns a re-arranged array (and leaves the original array un-changed).
print(random.permutation(x))

[1 2 3 4 5 6 7 8 9]
[1 5 9 7 6 2 8 4 3]
